#!/bin/bash

# Moritz Gelb
# April 2016

# Script to send status report of raspberry pi

# variables
MAIL="someone@somewhere.com"

# check for internet connetion, if false exit
ping -c 5 8.8.8.8 >/dev/null 2>/dev/null
if [ $? -eq 0 ]
        then
	INFO="Hello,\nI am online and will do your backups.\n\n\tCheers,\n\t backup-bot (running on raspberry pi)"
                LOGWARNING="Subject: [backup-bot] INFO: Raspberry Pi online\nFrom: backup-bot@raspberry-pi\nTo: $MAILTO\n\n$INFO"
                echo -e $LOGWARNING | sendmail $MAIL
fi
